USE jm_alpaca_venta;

-- =========================
-- TABLA: CLIENTE
-- =========================
CREATE TABLE CLIENTE (
    RUC_CLIENTE BIGINT NOT NULL,
    NOMBRE_CLIENTE VARCHAR(60) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (RUC_CLIENTE)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_spanish_ci;

-- =========================
-- TABLA: VENDEDOR
-- =========================
CREATE TABLE VENDEDOR (
    RUC_VENDEDOR BIGINT NOT NULL,
    NOMBRE_VENDEDOR VARCHAR(128) NOT NULL,
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (RUC_VENDEDOR)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_spanish_ci;

-- =========================
-- TABLA: VENTA
-- =========================
CREATE TABLE VENTA (
    ID_VENTA VARCHAR(20) NOT NULL,
    TIPO_VENTA VARCHAR(30),
    FECHA_DESPACHO DATE,
    RUC_VENDEDOR BIGINT NOT NULL,
    VENDEDOR VARCHAR(120) NULL,
    CODIGO_FACTURA VARCHAR(30) NULL,
    RUC_CLIENTE BIGINT NOT NULL,
    CLIENTE VARCHAR(120) NULL,    
    FACTURA_ANTICIPO VARCHAR(30),
    TIPO_MONEDA VARCHAR(10),
    IMPORTE_TOTAL DECIMAL(12,2),
    OBSERVACION VARCHAR(500),
    
    CONSTRAINT PK_VENTA PRIMARY KEY (ID_VENTA),

    CONSTRAINT FK_VENTA_CLIENTE
        FOREIGN KEY (RUC_CLIENTE)
        REFERENCES CLIENTE (RUC_CLIENTE),

    CONSTRAINT FK_VENTA_VENDEDOR
        FOREIGN KEY (RUC_VENDEDOR)
        REFERENCES VENDEDOR (RUC_VENDEDOR)

) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_spanish_ci;

-- =========================
-- TABLA: VENTA_DETALLE
-- =========================
CREATE TABLE VENTA_DETALLE (
    ID_DETALLE INT AUTO_INCREMENT NOT NULL,
    ID_VENTA VARCHAR(20) NOT NULL,
    PRODUCTO VARCHAR(100) NOT NULL,
    TIPO_PRODUCTO VARCHAR(50),
    PESO DECIMAL(10,2),
    DESCUENTO DECIMAL(10,2),
    CANTIDAD INT NOT NULL,
    UNIDAD_MEDIDA VARCHAR(20),
    VALOR_UNITARIO DECIMAL(10,2),
    IMPORTE_SUBTOTAL DECIMAL(12,2),

    CONSTRAINT PK_VENTA_DETALLE PRIMARY KEY (ID_DETALLE),

    CONSTRAINT FK_DETALLE_VENTA
        FOREIGN KEY (ID_VENTA)
        REFERENCES VENTA (ID_VENTA)
        ON DELETE CASCADE

) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_spanish_ci;

-- =========================================================
-- TABLA: VENTA_ERROR_CARGA
-- =========================================================
CREATE TABLE VENTA_ERROR_CARGA (
    ID_ERROR_CARGA BIGINT NOT NULL AUTO_INCREMENT,
    ID_VENTA VARCHAR(20) NOT NULL,
    CODIGO VARCHAR(20) NOT NULL,
    ERROR_CARGA VARCHAR(4000) NOT NULL,
    CONSTRAINT PK_VENTA_ERROR_CARGA PRIMARY KEY (ID_ERROR_CARGA)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_spanish_ci;



INSERT INTO CLIENTE (RUC_CLIENTE, NOMBRE_CLIENTE) VALUES
(20100192650, 'MICHELL Y CIA S.A.'),
(20100199743, 'INCA TOPS S.A.'),
(20455049564, 'PITATA S.A.C.'),
(20558036508, 'FILAVAL S.R.L.'),
(20603428774, 'MANUFACTURAS Y SERVICIOS S & P S.A.C.'),
(20604081841, 'GENERALES THOCHELLO SOCIEDAD ANONIMA CERRADA'),
(20610912762, 'PRIMAS TEXTILES DEL SUR S.R.L.');

INSERT INTO VENDEDOR (RUC_VENDEDOR, NOMBRE_VENDEDOR) VALUES
(10016891296, 'SALGUERO MAMANI GREGORIA ALFONZA'),
(10023732217, 'MAMANI COAQUIRA JACINTO'),
(10428954012, 'CHAINA CHURATA ALEX'),
(10432233591, 'QUISPE SALGUERO JOSE LUIS'),
(10454291846, 'MAMANI SALGUERO YOVANA'),
(10466379463, 'MAMANI SALGUERO EDISON GUIDO'),
(20608587030, 'COMERCIAL CHILI PACHOCA E.I.R.L.'),
(20611538287, 'COMERCIAL GOYTS S.R.L.');